In [1]:
import pandas as pd
import pickle
import datetime as dt
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 5000)

In [2]:
#from LogIn import LogIn
#kite = LogIn().return_kite_obj()

In [3]:
budget_df = pd.read_csv('budget_new.csv')

In [4]:
budget_df = budget_df[budget_df['instrument']!='NSE:MRF']

In [ ]:
budget_df['return'] = 0.05

In [ ]:
budget_df['budget'] = 25000

In [ ]:
budget_df

        instrument  budget  return
0      NSE:ACCELYA   25000    0.05
1     NSE:GOLDBEES   25000    0.05
2    NSE:GOLDSHARE   25000    0.05
3    NSE:NIFTYBEES   25000    0.05
4    NSE:POWERGRID   25000    0.05
5        NSE:WIPRO   25000    0.05
6       NSE:BIOCON   25000    0.05
7       NSE:COLPAL   25000    0.05
8   NSE:WABCOINDIA   25000    0.05
9   NSE:ASIANPAINT   25000    0.05
10       NSE:DABUR   25000    0.05
11  NSE:HINDUNILVR   25000    0.05
12   NSE:NESTLEIND   25000    0.05
13  NSE:ICICIBANKN   25000    0.05
14        NSE:IDFC   25000    0.05
15        NSE:INFY   25000    0.05
16   NSE:LICNFNHGP   25000    0.05
17      NSE:MARICO   25000    0.05
18  NSE:MUNJALSHOW   25000    0.05
19       NSE:NPBET   25000    0.05
20  NSE:TORNTPHARM   25000    0.05
21         NSE:ACC   25000    0.05
22    NSE:BANKBEES   25000    0.05
23   NSE:BATAINDIA   25000    0.05
24  NSE:BERGEPAINT   25000    0.05
25    NSE:HDFCBANK   25000    0.05
26  NSE:MCDOWELL-N   25000    0.05
28    NSE:SHREECEM   25000    0.05
29      NSE:VOLTAS   25000    0.05
30  NSE:AMARAJABAT   25000    0.05
31  NSE:APOLLOTYRE   25000    0.05
32  NSE:BAJAJ-AUTO   25000    0.05
33   NSE:BRITANNIA   25000    0.05
34  NSE:CUMMINSIND   25000    0.05
35     NSE:HAVELLS   25000    0.05
36  NSE:HEROMOTOCO   25000    0.05
37  NSE:IBVENTURES   25000    0.05
38     NSE:LINCOLN   25000    0.05
39          NSE:LT   25000    0.05
40  NSE:PIDILITIND   25000    0.05
41    NSE:RAMCOCEM   25000    0.05
42    NSE:TATACHEM   25000    0.05
43         NSE:TCS   25000    0.05
44       NSE:TITAN   25000    0.05
45    NSE:TVSMOTOR   25000    0.05
46  NSE:WOCKPHARMA   25000    0.05
47    NSE:BOSCHLTD   25000    0.05
48       NSE:CIPLA   25000    0.05
49   NSE:COALINDIA   25000    0.05
50    NSE:DIVISLAB   25000    0.05
51         NSE:DLF   25000    0.05
52     NSE:DRREDDY   25000    0.05
53   NSE:EICHERMOT   25000    0.05
54    NSE:GODREJCP   25000    0.05
55     NSE:HCLTECH   25000    0.05
56         NSE:IGL   25000    0.05
57         NSE:IOC   25000    0.05
58         NSE:ITC   25000    0.05
59       NSE:LUPIN   25000    0.05
60      NSE:NAUKRI   25000    0.05
61      NSE:RECLTD   25000    0.05
62    NSE:RELIANCE   25000    0.05
63  NSE:TORNTPOWER   25000    0.05
64   NSE:AMBUJACEM   25000    0.05
65  NSE:BHARTIARTL   25000    0.05
66    NSE:CADILAHC   25000    0.05
67        NSE:CESC   25000    0.05
68    NSE:EXIDEIND   25000    0.05
69        NSE:HDFC   25000    0.05
70    NSE:JSWSTEEL   25000    0.05
71      NSE:MARUTI   25000    0.05
72         NSE:MGL   25000    0.05
73        NSE:NTPC   25000    0.05
74         NSE:PFC   25000    0.05
75   NSE:SUNPHARMA   25000    0.05
76       NSE:SUNTV   25000    0.05
77   NSE:TATAPOWER   25000    0.05
78    NSE:HINDALCO   25000    0.05
79         NSE:M&M   25000    0.05
80  NSE:NATIONALUM   25000    0.05
81     NSE:PAGEIND   25000    0.05
82    NSE:PETRONET   25000    0.05
83     NSE:SIEMENS   25000    0.05
84       NSE:TECHM   25000    0.05
85  NSE:ULTRACEMCO   25000    0.05
86  NSE:AUROPHARMA   25000    0.05
87    NSE:GLENMARK   25000    0.05
88   NSE:HINDPETRO   25000    0.05
89        NSE:SBIN   25000    0.05
90   NSE:TATASTEEL   25000    0.05

# Inputs

In [ ]:
begin = "2015-02-01"
end = "2020-05-31"

In [ ]:
leverage = 15
exit_time = dt.time(15, 10)

# Process

In [ ]:
import datetime

# borrowed from https://stackoverflow.com/a/13565185
# as noted there, the calendar module has a function of its own
def last_day_of_month(any_day):
    next_month = any_day.replace(day=28) + datetime.timedelta(days=4)  # this will never fail
    return next_month - datetime.timedelta(days=next_month.day)

def monthlist(begin,end):
    begin = datetime.datetime.strptime(begin, "%Y-%m-%d")
    end = datetime.datetime.strptime(end, "%Y-%m-%d")

    result = []
    while True:
        if begin.month == 12:
            next_month = begin.replace(year=begin.year+1,month=1, day=1)
        else:
            next_month = begin.replace(month=begin.month+1, day=1)
        if next_month > end:
            break
        result.append ([begin.strftime("%Y-%m-%d"),last_day_of_month(begin).strftime("%Y-%m-%d")])
        begin = next_month
    result.append ([begin.strftime("%Y-%m-%d"),end.strftime("%Y-%m-%d")])
    return result


date_list = monthlist(begin,end)

In [ ]:
def get_clean_data(instrument):
    
    print(instrument)

    all_data_df = pd.DataFrame()

    for time_range in date_list:
        print(time_range)

        from_date = time_range[0]
        to_date = time_range[1]

        data_df = pd.read_pickle('./data_new/{}_{}_{}.pkl'.format(instrument, from_date, to_date))

        data_df.rename(columns={'date':'timestamp'}, inplace=True)
        data_df['date'] = data_df['timestamp'].dt.date
        data_df['day'] = data_df['timestamp'].dt.day_name()
        print(len(data_df))

        sanity_check = data_df.groupby('date').count().reset_index()
        incomplete_data_days = sanity_check[sanity_check['volume']<300]
        print(len(incomplete_data_days))

        data_df = data_df[~data_df['date'].isin(incomplete_data_days.date.tolist())]
        data_df['instrument'] = instrument
        print(len(data_df)/375)

        all_data_df = all_data_df.append(data_df, ignore_index=True)

    return all_data_df

In [ ]:
header_list = ['instrument', 'high_prev', 'low_prev', 'open_today', 'condition', 'transaction_type', 'trade_number', 'level', 'budget', 'return', 'daily_khwab', 'actual_khwab', 'quantity', 'budget_required', 'price', 'trigger_price', 'squareoff', 'stoploss', 'order_id', 'timestamp', 'order_type', 'status', 'profit', 'pl_tag', 'flag', 'adhoora_khwab']

In [ ]:
calculate = True

if calculate:
    
    all_trades = pd.DataFrame(columns=header_list)

    for instrument in budget_df.instrument.tolist():

        try:
            all_data_df = get_clean_data(instrument)

            for i in range(len(all_data_df.date.unique().tolist())-1):

                date_prev = all_data_df.date.unique().tolist()[i]
                data_prev = all_data_df[all_data_df['date']==date_prev]
                open_prev = data_prev.open.iloc[0]
                close_prev = data_prev.open.iloc[-1]
                high_prev = data_prev.high.max()
                low_prev = data_prev.low.min()

                date_today = all_data_df.date.unique().tolist()[i+1]
                data_today = all_data_df[all_data_df['date']==date_today]

                # Trim beyond exit time
                data_today = data_today[data_today['timestamp'].dt.time<exit_time]
                open_today = data_today.open.iloc[0]

                if (open_today > high_prev) & (open_today < 1.15 * high_prev):

                    condition = 'high'
                    transaction_type = 'sell'

                elif (open_today < low_prev) & (open_today > 0.85 * low_prev):

                    condition = 'low'
                    transaction_type = 'buy'

                else:

                    condition = None
                    transaction_type = None

                if condition is not None:

                    valid_trades = all_trades[(all_trades['instrument']==instrument) & (all_trades['condition']==condition) & (all_trades['status']=='complete')]
                    last_valid_trade = valid_trades[valid_trades['trade_number']==valid_trades['trade_number'].max()]

                    # Calculate trade number
                    if len(last_valid_trade):
                        trade_number = int(last_valid_trade['trade_number']) + 1
                    else:
                        trade_number = 1
                    
                    # Calculate level
                    if len(last_valid_trade):
                        if float(last_valid_trade['pl_tag'])==1.0:
                            level = 1
                        else:
                            level = float(last_valid_trade['level']) + 1
                    else:
                        level = 1

                    # Calculate budget and return
                    if level==1:
                        budget = float(budget_df[budget_df['instrument']==instrument]['budget'])
                        return_ = float(budget_df[budget_df['instrument']==instrument]['return'])
                    else:
                        budget = float(last_valid_trade['budget'])
                        return_ = float(last_valid_trade['return'])

                    # Calculate daily khwab
                    if len(last_valid_trade):
                        if int(last_valid_trade['pl_tag'])==1:
                            daily_khwab = round(return_ * budget, 2)
                        else:
                            daily_khwab = 0
                    else:
                        daily_khwab = round(return_ * budget, 2)

                    # Calculate actual khwab
                    if len(last_valid_trade):
                        actual_khwab = max(round(float(last_valid_trade['adhoora_khwab']) + daily_khwab, 2), round(return_ * budget, 2))
                    else:
                        actual_khwab = round(return_ * budget, 2)

                    # Caluclate tax
                    if actual_khwab > 5 * (round(return_ * budget, 2)):
                        factor = 1.5
                    else:
                        factor = 3
                        
                    tax = factor * (0.0005647 * actual_khwab)/return_
                    actual_khwab = round(actual_khwab + tax, 2)
                    
                    # Calculate quantity
                    quantity = int(round(actual_khwab/(return_ * open_today)))

                    # Calculate budget required
                    budget_required = round(quantity * open_today, 2)

                    # Calculate price and trigger price
                    if transaction_type=='buy':
                        price = round(open_today + 0.05 * max(round(20 * 0.006 * open_today), 2), 2)
                        trigger_price = round(open_today + 0.05 * max(round(20 * 0.005 * open_today),1), 2)
                    else:
                        price = round(open_today - 0.05 * max(round(20 * 0.006 * open_today), 2), 2)
                        trigger_price = round(open_today - 0.05 * max(round(20 * 0.005 * open_today),1), 2)

                    # Calculate square off and stoploss
                    squareoff = round(return_ * price, 1)
                    stoploss = round(return_ * price, 1)

                    # Calculate order_id, order_type
                    order_id = trade_number
                    order_type = 'SL'

                    # Calculate timestamp, status and profit
                    if transaction_type=='buy':
                        
                        if data_today.high.max() < trigger_price:

                            timestamp = data_today.timestamp.iloc[0]
                            status = 'incomplete'
                            profit = 0

                        else:

                            status = 'complete'
                            for index, row in data_today.iterrows():

                                if row['high'] > price + squareoff:
                                    timestamp = row['timestamp']
                                    profit = round(squareoff * quantity, 2)
                                    break

                                elif row['low'] < price - stoploss:
                                    timestamp = row['timestamp']
                                    profit = round(-1 * stoploss * quantity, 2)
                                    break

                                else:
                                    timestamp = row['timestamp']
                                    profit = round((row['close']-price) * quantity, 2)

                    else:

                        if data_today.low.min() > trigger_price:
                            timestamp = data_today.timestamp.iloc[0]
                            status = 'incomplete'
                            profit = 0        

                        else:

                            status = 'complete'
                            for index, row in data_today.iterrows():

                                if row['low'] < price - squareoff:
                                    timestamp = row['timestamp']
                                    profit = round(squareoff * quantity, 2)
                                    break

                                elif row['high'] > price + stoploss:
                                    timestamp = row['timestamp']
                                    profit = round(-1 * stoploss * quantity, 2)
                                    break

                                else:
                                    timestamp = row['timestamp']
                                    profit = round((price - row['close']) * quantity, 2)

                    # Calculate P/L tag
                    pl_tag = round(round(float(profit), 2) / (float(squareoff) * float(quantity)), 1)

                    # Calculate flag
                    if abs(float(pl_tag))==1:
                        flag = 1
                    else:
                        flag = 0

                    # Calculate adhoora khwab
                    adhoora_khwab = round(float(actual_khwab) - profit, 2)

                    trades_today = pd.DataFrame(data={'instrument':[instrument], 
                                                      'high_prev':[high_prev], 
                                                      'low_prev':[low_prev], 
                                                      'open_today':[open_today], 
                                                      'condition':[condition], 
                                                      'transaction_type':[transaction_type], 
                                                      'trade_number':[trade_number], 
                                                      'level':[level], 
                                                      'budget':[budget], 
                                                      'return':[return_], 
                                                      'daily_khwab':[daily_khwab], 
                                                      'actual_khwab':[actual_khwab], 
                                                      'quantity':[quantity], 
                                                      'budget_required':[budget_required], 
                                                      'price':[price], 
                                                      'trigger_price':[trigger_price], 
                                                      'squareoff':[squareoff], 
                                                      'stoploss':[stoploss], 
                                                      'order_id':[order_id], 
                                                      'timestamp':[timestamp], 
                                                      'order_type':[order_type], 
                                                      'status':[status], 
                                                      'profit':[profit], 
                                                      'pl_tag':[pl_tag], 
                                                      'flag':[flag], 
                                                      'adhoora_khwab':[adhoora_khwab]
                                                     })

                    all_trades = all_trades.append(trades_today, ignore_index = True)
        except Exception as ex:
            print('Failed calculation for {} : {}'.format(instrument, ex))
            
    all_trades.to_pickle('all_trades_opp_brokerage_return_newdata_{}_{}.pkl'.format(begin, end))
    
else:
    
    all_trades = pd.read_pickle('all_trades_opp_brokerage_return_newdata_trigger5_{}_{}.pkl'.format(begin, end))

NSE:ACCELYA
['2015-02-01', '2015-02-28']
7500
0
20.0
['2015-03-01', '2015-03-31']
7842
0
20.912
['2015-04-01', '2015-04-30']
7109
0
18.957333333333334
['2015-05-01', '2015-05-31']
7494
0
19.984
['2015-06-01', '2015-06-30']
8233
0
21.954666666666668
['2015-07-01', '2015-07-31']
8568
0
22.848
['2015-08-01', '2015-08-31']
7831
0
20.882666666666665
['2015-09-01', '2015-09-30']
7442
0
19.845333333333333
['2015-10-01', '2015-10-31']
7435
0
19.826666666666668
['2015-11-01', '2015-11-30']
6752
1
17.84
['2015-12-01', '2015-12-31']
7949
1
20.504
['2016-01-01', '2016-01-31']
7017
0
18.712
['2016-02-01', '2016-02-29']
7606
1
19.576
['2016-03-01', '2016-03-31']
7203
1
18.44
['2016-04-01', '2016-04-30']
6574
0
17.530666666666665
['2016-05-01', '2016-05-31']
8196
0
21.856
['2016-06-01', '2016-06-30']
8105
0
21.613333333333333
['2016-07-01', '2016-07-31']
7397
0
19.72533333333333
['2016-08-01', '2016-08-31']
8017
0
21.378666666666668
['2016-09-01', '2016-09-30']
7459
0
19.890666666666668
['2016-10-01', '2016-10-31']
6768
1
17.890666666666668
['2016-11-01', '2016-11-30']
7814
0
20.837333333333333
['2016-12-01', '2016-12-31']
8112
0
21.632
['2017-01-01', '2017-01-31']
7813
0
20.834666666666667
['2017-02-01', '2017-02-28']
7099
0
18.930666666666667
['2017-03-01', '2017-03-31']
8228
0
21.941333333333333
['2017-04-01', '2017-04-30']
6711
0
17.896
['2017-05-01', '2017-05-31']
8171
0
21.78933333333333
['2017-06-01', '2017-06-30']
7816
0
20.842666666666666
['2017-07-01', '2017-07-31']
7612
1
19.856
['2017-08-01', '2017-08-31']
7732
0
20.618666666666666
['2017-09-01', '2017-09-30']
7812
0
20.832
['2017-10-01', '2017-10-31']
7134
1
18.866666666666667
['2017-11-01', '2017-11-30']
8210
0
21.893333333333334
['2017-12-01', '2017-12-31']
7439
0
19.837333333333333
['2018-01-01', '2018-01-31']
8163
0
21.768
['2018-02-01', '2018-02-28']
7052
0
18.805333333333333
['2018-03-01', '2018-03-31']
7031
0
18.749333333333333
['2018-04-01', '2018-04-30']
7764
0
20.704
['2018-05-01', '2018-05-31']
8177
0
21.805333333333333
['2018-06-01', '2018-06-30']
7823
0
20.861333333333334
['2018-07-01', '2018-07-31']
8162
0
21.765333333333334
['2018-08-01', '2018-08-31']
7858
0
20.954666666666668
['2018-09-01', '2018-09-30']
6745
0
17.986666666666668
['2018-10-01', '2018-10-31']
7851
0
20.936
['2018-11-01', '2018-11-30']
7149
1
18.904
['2018-12-01', '2018-12-31']
6092
9
10.901333333333334
['2019-01-01', '2019-01-31']
5807
20
2.9466666666666668
['2019-02-01', '2019-02-28']
5218
17
2.6293333333333333
['2019-03-01', '2019-03-31']
5024
17
1.6266666666666667
['2019-04-01', '2019-04-30']
4873
19
0.0
['2019-05-01', '2019-05-31']
5885
17
4.256
['2019-06-01', '2019-06-30']
4734
18
0.808
['2019-07-01', '2019-07-31']
5326
23
0.0
['2019-08-01', '2019-08-31']
4713
20
0.0
['2019-09-01', '2019-09-30']
4375
17
1.6613333333333333
['2019-10-01', '2019-10-31']
4900
18
1.8613333333333333
['2019-11-01', '2019-11-30']
5926
11
8.272
['2019-12-01', '2019-12-31']
5564
19
1.7173333333333334
['2020-01-01', '2020-01-31']
5737
22
0.88
['2020-02-01', '2020-02-29']
5059
17
2.474666666666667
['2020-03-01', '2020-03-31']
5612
17
3.4426666666666668
['2020-04-01', '2020-04-30']
5521
8
9.186666666666667
['2020-05-01', '2020-05-31']
5335
1
13.541333333333334
NSE:GOLDBEES
['2015-02-01', '2015-02-28']
7500
0
20.0
['2015-03-01', '2015-03-31']
7841
0
20.909333333333333
['2015-04-01', '2015-04-30']
7121
0
18.989333333333335
['2015-05-01', '2015-05-31']
7500
0
20.0
['2015-06-01', '2015-06-30']
8250
0
22.0
['2015-07-01', '2015-07-31']
8621
0
22.989333333333335
['2015-08-01', '2015-08-31']
7871
0
20.989333333333335
['2015-09-01', '2015-09-30']
7483
0
19.954666666666668
['2015-10-01', '2015-10-31']
7498
0
19.994666666666667
['2015-11-01', '2015-11-30']
6811
1
18.0
['2015-12-01', '2015-12-31']
8232
0
21.952
['2016-01-01', '2016-01-31']
7123
0
18.994666666666667
['2016-02-01', '2016-02-29']
7875
0
21.0
['2016-03-01', '2016-03-31']
7497
0
19.992
['2016-04-01', '2016-04-30']
6750
0
18.0
['2016-05-01', '2016-05-31']
8250
0
22.0
['2016-06-01', '2016-06-30']
8250
0
22.0
['2016-07-01', '2016-07-31']
7499
0
19.997333333333334
['2016-08-01', '2016-08-31']
8247
0
21.992
['2016-09-01', '2016-09-30']
7496
0
19.989333333333335
['2016-10-01', '2016-10-31']
6809
1
17.997333333333334
['2016-11-01', '2016-11-30']
7874
0
20.997333333333334
['2016-12-01', '2016-12-31']
8248
0
21.994666666666667
['2017-01-01', '2017-01-31']
7873
0
20.994666666666667
['2017-02-01', '2017-02-28']
7121
0
18.989333333333335
['2017-03-01', '2017-03-31']
8247
0
21.992
['2017-04-01', '2017-04-30']
6745
0
17.986666666666668
['2017-05-01', '2017-05-31']
8249
0
21.997333333333334
['2017-06-01', '2017-06-30']
7867
0
20.978666666666665
['2017-07-01', '2017-07-31']
7680
1
20.0
['2017-08-01', '2017-08-31']
7874
0
20.997333333333334
['2017-09-01', '2017-09-30']
7874
0
20.997333333333334
['2017-10-01', '2017-10-31']
7185
1
19.0
['2017-11-01', '2017-11-30']
8246
0
21.989333333333335
['2017-12-01', '2017-12-31']
7497
0
19.992
['2018-01-01', '2018-01-31']
8250
0
22.0
['2018-02-01', '2018-02-28']
7124
0
18.997333333333334
['2018-03-01', '2018-03-31']
7119
0
18.984
['2018-04-01', '2018-04-30']
7873
0
20.994666666666667
['2018-05-01', '2018-05-31']
8245
0
21.986666666666668
['2018-06-01', '2018-06-30']
7874
0
20.997333333333334
['2018-07-01', '2018-07-31']
8250
0
22.0
['2018-08-01', '2018-08-31']
7874
0
20.997333333333334
['2018-09-01', '2018-09-30']
6749
0
17.997333333333334
['2018-10-01', '2018-10-31']
7875
0
21.0
['2018-11-01', '2018-11-30']
7185
1
19.0
['2018-12-01', '2018-12-31']
7379
0
19.677333333333333
['2019-01-01', '2019-01-31']
8317
0
22.17866666666667
['2019-02-01', '2019-02-28']
7143
0
19.048
['2019-03-01', '2019-03-31']
6858
0
18.288
['2019-04-01', '2019-04-30']
6705
0
17.88
['2019-05-01', '2019-05-31']
7799
0
20.797333333333334
['2019-06-01', '2019-06-30']
6919
0
18.450666666666667
['2019-07-01', '2019-07-31']
8257
0
22.018666666666668
['2019-08-01', '2019-08-31']
7454
0
19.877333333333333
['2019-09-01', '2019-09-30']
7048
0
18.794666666666668
['2019-10-01', '2019-10-31']
7065
1
18.68
['2019-11-01', '2019-11-30']
7361
0
19.629333333333335
['2019-12-01', '2019-12-31']
7721
0
20.589333333333332
['2020-01-01', '2020-01-31']
8622
0
22.992
['2020-02-01', '2020-02-29']
7496
0
19.989333333333335
['2020-03-01', '2020-03-31']
7757
0
20.685333333333332
['2020-04-01', '2020-04-30']
6751
0
18.002666666666666
['2020-05-01', '2020-05-31']
5625
0
15.0
NSE:GOLDSHARE
['2015-02-01', '2015-02-28']
7499
0
19.997333333333334
['2015-03-01', '2015-03-31']
7841
0
20.909333333333333
['2015-04-01', '2015-04-30']
7121
0
18.989333333333335
['2015-05-01', '2015-05-31']
7495
0
19.986666666666668
['2015-06-01', '2015-06-30']
8250
0
22.0
['2015-07-01', '2015-07-31']
8616
0
22.976
['2015-08-01', '2015-08-31']
7844
0
20.917333333333332
['2015-09-01', '2015-09-30']
7467
0
19.912
['2015-10-01', '2015-10-31']
7458
0
19.888
['2015-11-01', '2015-11-30']
6800
1
17.970666666666666
['2015-12-01', '2015-12-31']
8211
0
21.896
['2016-01-01', '2016-01-31']
7124
0
18.997333333333334
['2016-02-01', '2016-02-29']
7874
0
20.997333333333334
['2016-03-01', '2016-03-31']
7481
0
19.949333333333332
['2016-04-01', '2016-04-30']
6725
0
17.933333333333334
['2016-05-01', '2016-05-31']
8242
0
21.978666666666665
['2016-06-01', '2016-06-30']
8216
0
21.909333333333333
['2016-07-01', '2016-07-31']
7472
0
19.925333333333334
['2016-08-01', '2016-08-31']
8192
0
21.845333333333333
['2016-09-01', '2016-09-30']
7448
0
19.861333333333334
['2016-10-01', '2016-10-31']
6794
1
17.957333333333334
['2016-11-01', '2016-11-30']
7803
0
20.808
['2016-12-01', '2016-12-31']
8207
0
21.88533333333333
['2017-01-01', '2017-01-31']
7821
0
20.856
['2017-02-01', '2017-02-28']
7018
0
18.714666666666666
['2017-03-01', '2017-03-31']
8199
0
21.864
['2017-04-01', '2017-04-30']
6715
0
17.906666666666666
['2017-05-01', '2017-05-31']
8138
0
21.701333333333334
['2017-06-01', '2017-06-30']
7803
0
20.808
['2017-07-01', '2017-07-31']
7615
1
19.826666666666668
['2017-08-01', '2017-08-31']
7772
0
20.72533333333333
['2017-09-01', '2017-09-30']
7753
0
20.674666666666667
['2017-10-01', '2017-10-31']
7168
1
18.954666666666668
['2017-11-01', '2017-11-30']
8117
0
21.645333333333333
['2017-12-01', '2017-12-31']
7424
0
19.797333333333334
['2018-01-01', '2018-01-31']

8141
0
21.709333333333333
['2018-02-01', '2018-02-28']
6790
0
18.106666666666666
['2018-03-01', '2018-03-31']
6995
0
18.653333333333332
['2018-04-01', '2018-04-30']
7772
0
20.72533333333333
['2018-05-01', '2018-05-31']
8093
0
21.581333333333333
['2018-06-01', '2018-06-30']
7684
0
20.490666666666666
['2018-07-01', '2018-07-31']
8165
0
21.773333333333333
['2018-08-01', '2018-08-31']
7795
0
20.786666666666665
['2018-09-01', '2018-09-30']
6539
0
17.437333333333335
['2018-10-01', '2018-10-31']
7730
0
20.613333333333333
['2018-11-01', '2018-11-30']
7113
1
18.808
['2018-12-01', '2018-12-31']
5830
9
10.808
['2019-01-01', '2019-01-31']
4919
20
3.0
['2019-02-01', '2019-02-28']
3823
20
0.0
['2019-03-01', '2019-03-31']
3229
19
0.0
['2019-04-01', '2019-04-30']
2853
19
0.0
['2019-05-01', '2019-05-31']
3642
21
0.8826666666666667
['2019-06-01', '2019-06-30']
3948
19
0.0
['2019-07-01', '2019-07-31']
4291
23
0.0
['2019-08-01', '2019-08-31']
5198
19
0.8213333333333334
['2019-09-01', '2019-09-30']
4809
18
0.8213333333333334
['2019-10-01', '2019-10-31']
4483
19
0.8853333333333333
['2019-11-01', '2019-11-30']
4284
20
0.0
['2019-12-01', '2019-12-31']
3943
21
0.0
['2020-01-01', '2020-01-31']
5327
19
3.3333333333333335
['2020-02-01', '2020-02-29']
4594
18
1.7013333333333334
['2020-03-01', '2020-03-31']
6034
12
7.504
['2020-04-01', '2020-04-30']
5843
3
13.298666666666668
['2020-05-01', '2020-05-31']
4258
11
3.458666666666667
NSE:NIFTYBEES
['2015-02-01', '2015-02-28']
7500
0
20.0
['2015-03-01', '2015-03-31']
7842
0
20.912
['2015-04-01', '2015-04-30']
7121
0
18.989333333333335
['2015-05-01', '2015-05-31']
7500
0
20.0
['2015-06-01', '2015-06-30']
8250
0
22.0
['2015-07-01', '2015-07-31']
8621
0
22.989333333333335
['2015-08-01', '2015-08-31']
7872
0
20.992
['2015-09-01', '2015-09-30']
7483
0
19.954666666666668
['2015-10-01', '2015-10-31']
7499
0
19.997333333333334
['2015-11-01', '2015-11-30']
6810
1
17.997333333333334
['2015-12-01', '2015-12-31']
8226
0
21.936
['2016-01-01', '2016-01-31']
7125
0
19.0
['2016-02-01', '2016-02-29']
7875
0
21.0
['2016-03-01', '2016-03-31']
7500
0
20.0
['2016-04-01', '2016-04-30']
6750
0
18.0
['2016-05-01', '2016-05-31']
8250
0
22.0
['2016-06-01', '2016-06-30']
8250
0
22.0
['2016-07-01', '2016-07-31']
7499
0
19.997333333333334
['2016-08-01', '2016-08-31']
8250
0
22.0
['2016-09-01', '2016-09-30']
7499
0
19.997333333333334
['2016-10-01', '2016-10-31']
6810
1
18.0
['2016-11-01', '2016-11-30']
7875
0
21.0
['2016-12-01', '2016-12-31']
8250
0
22.0
['2017-01-01', '2017-01-31']
7875
0
21.0
['2017-02-01', '2017-02-28']
7125
0
19.0
['2017-03-01', '2017-03-31']
8250
0
22.0
['2017-04-01', '2017-04-30']
6750
0
18.0
['2017-05-01', '2017-05-31']
8250
0
22.0
['2017-06-01', '2017-06-30']
7874
0
20.997333333333334
['2017-07-01', '2017-07-31']
7680
1
20.0
['2017-08-01', '2017-08-31']
7869
0
20.984
['2017-09-01', '2017-09-30']
7875
0
21.0
['2017-10-01', '2017-10-31']
7185
1
19.0
['2017-11-01', '2017-11-30']
8250
0
22.0
['2017-12-01', '2017-12-31']
7500
0
20.0
['2018-01-01', '2018-01-31']
8248
0
21.994666666666667
['2018-02-01', '2018-02-28']
7125
0
19.0
['2018-03-01', '2018-03-31']
7124
0
18.997333333333334
['2018-04-01', '2018-04-30']
7869
0
20.984
['2018-05-01', '2018-05-31']
8247
0
21.992
['2018-06-01', '2018-06-30']
7872
0
20.992
['2018-07-01', '2018-07-31']
8245
0
21.986666666666668
['2018-08-01', '2018-08-31']
7872
0
20.992
['2018-09-01', '2018-09-30']
6750
0
18.0
['2018-10-01', '2018-10-31']
7875
0
21.0
['2018-11-01', '2018-11-30']
7185
1
19.0
['2018-12-01', '2018-12-31']
7499
0
19.997333333333334
['2019-01-01', '2019-01-31']
8625
0
23.0
['2019-02-01', '2019-02-28']
7500
0
20.0
['2019-03-01', '2019-03-31']
7125
0
19.0
['2019-04-01', '2019-04-30']
7125
0
19.0
['2019-05-01', '2019-05-31']
8247
0
21.992
['2019-06-01', '2019-06-30']
7124
0
18.997333333333334
['2019-07-01', '2019-07-31']
8607
0
22.952
['2019-08-01', '2019-08-31']
7494
0
19.984
['2019-09-01', '2019-09-30']
7107
0
18.952
['2019-10-01', '2019-10-31']
7183
1
18.994666666666667
['2019-11-01', '2019-11-30']
7495
0
19.986666666666668
['2019-12-01', '2019-12-31']
7875
0
21.0
['2020-01-01', '2020-01-31']
8625
0
23.0
['2020-02-01', '2020-02-29']
7499
0
19.997333333333334
['2020-03-01', '2020-03-31']
7757
0
20.685333333333332
['2020-04-01', '2020-04-30']
6750
0
18.0
['2020-05-01', '2020-05-31']
5625
0
15.0
NSE:POWERGRID
['2015-02-01', '2015-02-28']
7500
0
20.0
['2015-03-01', '2015-03-31']
7842
0
20.912
['2015-04-01', '2015-04-30']
7121
0
18.989333333333335
['2015-05-01', '2015-05-31']
7500
0
20.0
['2015-06-01', '2015-06-30']
8250
0
22.0
['2015-07-01', '2015-07-31']
8621
0
22.989333333333335
['2015-08-01', '2015-08-31']
7871
0
20.989333333333335
['2015-09-01', '2015-09-30']
7483
0
19.954666666666668
['2015-10-01', '2015-10-31']
7500
0
20.0
['2015-11-01', '2015-11-30']
6812
1
18.0
['2015-12-01', '2015-12-31']
8226
0
21.936
['2016-01-01', '2016-01-31']
7125
0
19.0
['2016-02-01', '2016-02-29']
7875
0
21.0
['2016-03-01', '2016-03-31']
7500
0
20.0
['2016-04-01', '2016-04-30']
6750
0
18.0
['2016-05-01', '2016-05-31']
8250
0
22.0
['2016-06-01', '2016-06-30']
8250
0
22.0
['2016-07-01', '2016-07-31']
7500
0
20.0
['2016-08-01', '2016-08-31']
8250
0
22.0
['2016-09-01', '2016-09-30']
7500
0
20.0
['2016-10-01', '2016-10-31']
6810
1
18.0
['2016-11-01', '2016-11-30']
7875
0
21.0
['2016-12-01', '2016-12-31']
8250
0
22.0
['2017-01-01', '2017-01-31']
7875
0
21.0
['2017-02-01', '2017-02-28']
7125
0
19.0
['2017-03-01', '2017-03-31']
8250
0
22.0
['2017-04-01', '2017-04-30']
6750
0
18.0
['2017-05-01', '2017-05-31']
8250
0
22.0
['2017-06-01', '2017-06-30']
7875
0
21.0
['2017-07-01', '2017-07-31']
7680
1
20.0
['2017-08-01', '2017-08-31']
7875
0
21.0
['2017-09-01', '2017-09-30']
7875
0
21.0
['2017-10-01', '2017-10-31']
7185
1
19.0
['2017-11-01', '2017-11-30']
8250
0
22.0
['2017-12-01', '2017-12-31']
7500
0
20.0
['2018-01-01', '2018-01-31']
8250
0
22.0
['2018-02-01', '2018-02-28']
7125
0
19.0
['2018-03-01', '2018-03-31']
7125
0
19.0
['2018-04-01', '2018-04-30']
7875
0
21.0
['2018-05-01', '2018-05-31']
8250
0
22.0
['2018-06-01', '2018-06-30']
7875
0
21.0
['2018-07-01', '2018-07-31']
8250
0
22.0
['2018-08-01', '2018-08-31']
7875
0
21.0
['2018-09-01', '2018-09-30']
6750
0
18.0
['2018-10-01', '2018-10-31']
7875
0
21.0
['2018-11-01', '2018-11-30']
7185
1
19.0
['2018-12-01', '2018-12-31']
7500
0
20.0
['2019-01-01', '2019-01-31']
8625
0
23.0
['2019-02-01', '2019-02-28']
7500
0
20.0
['2019-03-01', '2019-03-31']
7125
0
19.0
['2019-04-01', '2019-04-30']
7125
0
19.0
['2019-05-01', '2019-05-31']
8247
0
21.992
['2019-06-01', '2019-06-30']
7125
0
19.0
['2019-07-01', '2019-07-31']
8625
0
23.0
['2019-08-01', '2019-08-31']
7499
0
19.997333333333334
['2019-09-01', '2019-09-30']
7110
0
18.96
['2019-10-01', '2019-10-31']
7185
1
19.0
['2019-11-01', '2019-11-30']
7500
0
20.0
['2019-12-01', '2019-12-31']
7875
0
21.0
['2020-01-01', '2020-01-31']
8625
0
23.0
['2020-02-01', '2020-02-29']
7499
0
19.997333333333334
['2020-03-01', '2020-03-31']
7757
0
20.685333333333332
['2020-04-01', '2020-04-30']
6751
0
18.002666666666666
['2020-05-01', '2020-05-31']
5625
0
15.0
NSE:WIPRO
['2015-02-01', '2015-02-28']
7500
0
20.0
['2015-03-01', '2015-03-31']
7842
0
20.912
['2015-04-01', '2015-04-30']
7121
0
18.989333333333335
['2015-05-01', '2015-05-31']
7500
0
20.0
['2015-06-01', '2015-06-30']
8250
0
22.0
['2015-07-01', '2015-07-31']
8621
0
22.989333333333335
['2015-08-01', '2015-08-31']
7870
0
20.986666666666668
['2015-09-01', '2015-09-30']
7483
0
19.954666666666668
['2015-10-01', '2015-10-31']
7500
0
20.0
['2015-11-01', '2015-11-30']
6812
1
18.0
['2015-12-01', '2015-12-31']
8227
0
21.938666666666666
['2016-01-01', '2016-01-31']
7125
0
19.0
['2016-02-01', '2016-02-29']
7875
0
21.0
['2016-03-01', '2016-03-31']
7500
0
20.0
['2016-04-01', '2016-04-30']
6750
0
18.0
['2016-05-01', '2016-05-31']
8250
0
22.0
['2016-06-01', '2016-06-30']
8250
0
22.0
['2016-07-01', '2016-07-31']
7500
0
20.0
['2016-08-01', '2016-08-31']
8250
0
22.0
['2016-09-01', '2016-09-30']
7500
0
20.0
['2016-10-01', '2016-10-31']
6810
1
18.0
['2016-11-01', '2016-11-30']
7875
0
21.0
['2016-12-01', '2016-12-31']
8250
0
22.0
['2017-01-01', '2017-01-31']
7875
0
21.0
['2017-02-01', '2017-02-28']
7125
0
19.0
['2017-03-01', '2017-03-31']
8250
0
22.0
['2017-04-01', '2017-04-30']
6750
0
18.0
['2017-05-01', '2017-05-31']
8250
0
22.0

['2017-06-01', '2017-06-30']
7875
0
21.0
['2017-07-01', '2017-07-31']
7680
1
20.0
['2017-08-01', '2017-08-31']
7875
0
21.0
['2017-09-01', '2017-09-30']
7875
0
21.0
['2017-10-01', '2017-10-31']
7185
1
19.0
['2017-11-01', '2017-11-30']
8250
0
22.0
['2017-12-01', '2017-12-31']
7500
0
20.0
['2018-01-01', '2018-01-31']
8250
0
22.0
['2018-02-01', '2018-02-28']
7125
0
19.0
['2018-03-01', '2018-03-31']
7125
0
19.0
['2018-04-01', '2018-04-30']
7875
0
21.0
['2018-05-01', '2018-05-31']
8250
0
22.0
['2018-06-01', '2018-06-30']
7875
0
21.0
['2018-07-01', '2018-07-31']
8250
0
22.0
['2018-08-01', '2018-08-31']
7875
0
21.0
['2018-09-01', '2018-09-30']
6750
0
18.0
['2018-10-01', '2018-10-31']
7875
0
21.0
['2018-11-01', '2018-11-30']
7185
1
19.0
['2018-12-01', '2018-12-31']
7500
0
20.0
['2019-01-01', '2019-01-31']
8625
0
23.0
['2019-02-01', '2019-02-28']
7500
0
20.0
['2019-03-01', '2019-03-31']
7125
0
19.0
['2019-04-01', '2019-04-30']
7125
0
19.0
['2019-05-01', '2019-05-31']
8247
0
21.992
['2019-06-01', '2019-06-30']
7125
0
19.0
['2019-07-01', '2019-07-31']
8625
0
23.0
['2019-08-01', '2019-08-31']
7499
0
19.997333333333334
['2019-09-01', '2019-09-30']
7110
0
18.96
['2019-10-01', '2019-10-31']
7185
1
19.0
['2019-11-01', '2019-11-30']
7500
0
20.0
['2019-12-01', '2019-12-31']
7875
0
21.0
['2020-01-01', '2020-01-31']
8625
0
23.0
['2020-02-01', '2020-02-29']
7499
0
19.997333333333334
['2020-03-01', '2020-03-31']
7757
0
20.685333333333332
['2020-04-01', '2020-04-30']
6750
0
18.0
['2020-05-01', '2020-05-31']
5625
0
15.0

# High Trades Analysis

In [ ]:
all_trades['new_timestamp'] = all_trades.apply(lambda s: s['timestamp'].tz_convert(None), axis=1)

In [ ]:
all_trades[~all_trades['instrument'].isin(less_100)].instrument.nunique()

In [ ]:
high_trades = all_trades[(all_trades['condition']=='high') & (all_trades['status']=='complete') & (~all_trades['instrument'].isin(less_100)) & (all_trades['new_timestamp']<pd.to_datetime('2019-12-31'))]

In [ ]:
high_trades_loop = pd.DataFrame()
for instrument in high_trades.instrument.unique().tolist():
    instrument_high_trades = high_trades[high_trades['instrument']==instrument]
    instrument_high_trades_loop = instrument_high_trades[instrument_high_trades['trade_number']<=instrument_high_trades[instrument_high_trades['pl_tag']==1.0].trade_number.max()]
    high_trades_loop = high_trades_loop.append(instrument_high_trades_loop, ignore_index=True)

In [ ]:
high_trades.head()

In [ ]:
high_trades.instrument.nunique()

In [ ]:
high_trades.groupby(['instrument']).agg({'profit':sum, 'budget_required':max}).reset_index()

In [ ]:
high_trades_loop.groupby(['instrument']).agg({'profit':sum, 'budget_required':max}).reset_index()

# Low Trades Analysis

In [ ]:
low_trades = all_trades[(all_trades['condition']=='low') & (all_trades['status']=='complete') & (~all_trades['instrument'].isin(less_100)) & (all_trades['new_timestamp']<pd.to_datetime('2019-12-31'))]

In [ ]:
low_trades_loop = pd.DataFrame()
for instrument in low_trades.instrument.unique().tolist():
    instrument_low_trades = low_trades[low_trades['instrument']==instrument]
    instrument_low_trades_loop = instrument_low_trades[instrument_low_trades['trade_number']<=instrument_low_trades[instrument_low_trades['pl_tag']==1.0].trade_number.max()]
    low_trades_loop = low_trades_loop.append(instrument_low_trades_loop, ignore_index=True)

In [ ]:
low_trades.head()

In [ ]:
low_trades.instrument.nunique()

In [ ]:
low_trades.groupby(['instrument']).agg({'profit':sum, 'budget_required':max}).reset_index()

In [ ]:
low_trades_loop.groupby(['instrument']).agg({'profit':sum, 'budget_required':max}).reset_index()

# Results

In [ ]:
pd.DataFrame(data={'high':[len(high_trades),
                           len(high_trades_loop),
                           round(high_trades_loop.profit.sum(), 2), 
                           round(high_trades_loop.profit.sum()/budget_df.budget.sum() * 100, 2),
                           round(high_trades_loop.budget_required.max()), 
                           round(high_trades_loop.budget_required.max()/leverage)],
                   'low':[len(low_trades),
                          len(low_trades_loop),
                          round(low_trades_loop.profit.sum(), 2), 
                          round(low_trades_loop.profit.sum()/budget_df.budget.sum() * 100, 2),
                          round(low_trades_loop.budget_required.max()),
                          round(low_trades_loop.budget_required.max()/leverage)]
                   }, 
             index = ['total_trades', 'trades_considered', 'profit', 'perc_return', 'hightest_budget_required', 'hightest_margin_required'])

In [ ]:
pd.DataFrame(data={'high':[len(high_trades),
                           len(high_trades),
                           round(high_trades.profit.sum(), 2), 
                           round(high_trades.profit.sum()/budget_df.budget.sum() * 100, 2),
                           round(high_trades.budget_required.max()), 
                           round(high_trades.budget_required.max()/leverage)],
                   'low':[len(low_trades),
                          len(low_trades),
                          round(low_trades.profit.sum(), 2), 
                          round(low_trades.profit.sum()/budget_df.budget.sum() * 100, 2),
                          round(low_trades.budget_required.max()),
                          round(low_trades.budget_required.max()/leverage)]
                   }, 
             index = ['total_trades', 'trades_considered', 'profit', 'perc_return', 'hightest_budget_required', 'hightest_margin_required'])

# Daily Margin Required Analysis

In [ ]:
all_trades['date'] = all_trades['timestamp'].dt.date
all_trades['margin_required'] = all_trades['budget_required']/leverage
margins = all_trades.groupby('date').agg({'budget_required':sum, 'margin_required':sum, 'instrument':list}).reset_index()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def stacked_bar(data, series_labels, category_labels=None, 
                show_values=False, value_format="{}", y_label=None, 
                grid=True, reverse=False):
    """Plots a stacked bar chart with the data and labels provided.

    Keyword arguments:
    data            -- 2-dimensional numpy array or nested list
                       containing data for each series in rows
    series_labels   -- list of series labels (these appear in
                       the legend)
    category_labels -- list of category labels (these appear
                       on the x-axis)
    show_values     -- If True then numeric value labels will 
                       be shown on each bar
    value_format    -- Format string for numeric value labels
                       (default is "{}")
    y_label         -- Label for y-axis (str)
    grid            -- If True display grid
    reverse         -- If True reverse the order that the
                       series are displayed (left-to-right
                       or right-to-left)
    """

    ny = len(data[0])
    ind = list(range(ny))

    axes = []
    cum_size = np.zeros(ny)

    data = np.array(data)

    if reverse:
        data = np.flip(data, axis=1)
        category_labels = reversed(category_labels)

    for i, row_data in enumerate(data):
        axes.append(plt.bar(ind, row_data, bottom=cum_size, 
                            label=series_labels[i]))
        cum_size += row_data

    if category_labels:
        plt.xticks(ind, category_labels, rotation='vertical')

    if y_label:
        plt.ylabel(y_label)

    plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))

    if grid:
        plt.grid()

    if show_values:
        for axis in axes:
            for bar in axis:
                w, h = bar.get_width(), bar.get_height()
                plt.text(bar.get_x() + w/2, bar.get_y() + h/2, 
                         value_format.format(h), ha="center", 
                         va="center")

In [ ]:
df2 = all_trades.groupby(['date', 'instrument'])['margin_required'].sum().unstack('instrument').fillna(0)

df2['date'] = df2[df2['date'] < '2019/12/31']
df = df2.transpose()

plt.figure(figsize=(50, 10))

series_labels = df.index.tolist()

data = df.values

category_labels = df.columns.tolist()

stacked_bar(
    data, 
    series_labels, 
    category_labels=category_labels, 
    show_values=False,
    value_format="{:.1f}",
    y_label="Total margin required"
)

plt.savefig('margin_required_opp_brokerage_return_newdata_trigger5_{}_{}.png'.format(begin, end))
plt.show()

## Brokerage Calculation

In [ ]:
# brokerage = min(40, 0.0002 * budget_required)
# stt = 0.00025 * budget_required
# transaction_charges = 2 * 0.0000325 * budget_required
# gst = 0.18 * (brokerage + transaction_charges)
# sebi = 2 * 10 * budget_required/10000000
# total_tax_and_charges = brokerage + stt + transaction_charges + gst + sebi

# profit = profit - total_tax_and_charges

# Postmartem

In [ ]:
less_100 = all_trades[all_trades['low_prev']<100].instrument.unique().tolist()

In [ ]:
len(less_100)

In [ ]:
all_trades[~all_trades['instrument'].isin(less_100)].instrument.nunique()

In [ ]:
all_trades.instrument.nunique()

In [ ]:
set(budget_df.instrument.unique().tolist())-set(all_trades.instrument.unique().tolist())

In [ ]:
budget_df

In [ ]:
new_budget = budget_df[~budget_df.instrument.isin(less_100)]

In [ ]:
len(new_budget)

In [ ]:
new_budget

In [ ]:
low_trades[low_trades['budget_required']==low_trades['budget_required'].max()]

In [ ]:
low_trades[low_trades['instrument']=='NSE:ULTRACEMCO']