In [1]:
import pandas as pd
import datetime as dt
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 5000)

In [2]:
from LogIn import LogIn
kite = LogIn().return_kite_obj()

In [3]:
budget_df = pd.read_csv('budget.csv')

In [4]:
budget_df

        instrument  budget  return
0    NSE:UNIONBANK     400    0.02
1      NSE:DCBBANK     400    0.02
2      NSE:YESBANK     400    0.02
3        NSE:WIPRO     400    0.02
4    NSE:TATASTEEL     400    0.02
5         NSE:SBIN     400    0.02
6          NSE:PNB     400    0.02
7         NSE:ONGC     400    0.02
8          NSE:OIL     400    0.02
9         NSE:NTPC     400    0.02
10         NSE:BEL     400    0.02
11      NSE:BIOCON     400    0.02
12       NSE:CANBK     400    0.02
13  NSE:CASTROLIND     400    0.02
14    NSE:CHOLAFIN     400    0.02
15   NSE:COALINDIA     400    0.02
16  NSE:ENGINERSIN     400    0.02
17    NSE:EXIDEIND     400    0.02
18    NSE:JSWSTEEL     400    0.02
19  NSE:MANAPPURAM     400    0.02
20        NSE:SAIL     400    0.02
21      NSE:RECLTD     400    0.02
22        NSE:NMDC     400    0.02
23        NSE:MFSL     500    0.02
24        NSE:IDBI     400    0.02
25      NSE:ARVIND     400    0.02
26        NSE:BHEL     400    0.02
27  NSE:TATAMTRDVR     400    0.02
28   NSE:TATAPOWER     400    0.02
29  NSE:ADANIPOWER     400    0.02
30       NSE:BSOFT     400    0.02
31    NSE:ASHOKLEY     400    0.02
32         NSE:NCC     400    0.02
33   NSE:BANKINDIA     400    0.02
34  NSE:FEDERALBNK     400    0.02
35  NSE:MOTHERSUMI     400    0.02
36  NSE:BANKBARODA     400    0.02
37  NSE:JINDALSTEL     400    0.02
38       NSE:L&TFH     400    0.02
39         NSE:PFC     400    0.02
40     NSE:EQUITAS     400    0.02
41  NSE:TATAMOTORS     400    0.02
42         NSE:IOC     400    0.02
43    NSE:ADANIENT     400    0.02
44        NSE:GAIL     400    0.02
45        NSE:VEDL     400    0.02
46  NSE:APOLLOTYRE     400    0.02
47         NSE:DLF     400    0.02
48    NSE:HINDALCO     400    0.02
49   NSE:AMBUJACEM     400    0.02
50    NSE:HINDZINC     400    0.02
51    NSE:CADILAHC     400    0.02
52   NSE:POWERGRID     400    0.02
53   NSE:HINDPETRO     400    0.02
54    NSE:INFRATEL     400    0.02
55         NSE:ITC     400    0.02
56    NSE:PETRONET     400    0.02
57  NSE:TATAGLOBAL     400    0.02
58     NSE:UJJIVAN     400    0.02
59  NSE:TORNTPOWER     400    0.02
60         NSE:IGL     400    0.02
61  NSE:ADANIPORTS     400    0.02
62  NSE:BERGEPAINT     400    0.02
63        NSE:BPCL     400    0.02
64        NSE:ZEEL     400    0.02
65    NSE:GLENMARK     400    0.02
66  NSE:BHARTIARTL     400    0.02
67    NSE:TVSMOTOR     400    0.02
68    NSE:HEXAWARE     400    0.02
69  NSE:ICICIPRULI     400    0.02

# Inputs

In [5]:
instrument = 'NSE:ADANIPORTS'
from_date = '2018-01-01'
to_date = '2018-12-31'

In [6]:
assigned_budget = 400
assigned_return = 0.02
leverage = 15
exit_time = dt.time(15, 10)

# Process

In [7]:
instrument_token = kite.ohlc(instrument)[instrument]['instrument_token']

In [8]:
data = kite.historical_data(instrument_token=instrument_token, from_date=from_date, to_date=to_date, interval='minute', continuous=False)

In [9]:
data_df = pd.DataFrame(data)

In [10]:
len(data_df)

91935

In [11]:
data_df.rename(columns={'date':'timestamp'}, inplace=True)
data_df['date'] = data_df['timestamp'].dt.date
data_df['day'] = data_df['timestamp'].dt.day_name()

In [12]:
data_df.head()

,close,timestamp,high,low,open,volume,date,day
0,404.25,2018-01-01 09:15:00+05:30,407.00,403.70,407.00,15018,2018-01-01,Monday
1,404.50,2018-01-01 09:16:00+05:30,404.90,403.30,404.55,12209,2018-01-01,Monday
2,405.50,2018-01-01 09:17:00+05:30,406.30,404.55,404.55,7837,2018-01-01,Monday
3,404.70,2018-01-01 09:18:00+05:30,405.65,404.60,405.55,3614,2018-01-01,Monday
4,404.55,2018-01-01 09:19:00+05:30,405.10,404.20,405.10,4542,2018-01-01,Monday

In [13]:
sanity_check = data_df.groupby('date').count().reset_index()

In [14]:
incomplete_data_days = sanity_check[sanity_check['volume']!=375]

In [15]:
incomplete_data_days

           date  close  timestamp  high  low  open  volume  day
210  2018-11-07     60         60    60   60    60      60   60

In [16]:
data_df = data_df[~data_df['date'].isin(incomplete_data_days.date.tolist())]

In [17]:
len(data_df)

91875

In [18]:
len(data_df)/375

245.0

In [19]:
header_list = ['instrument', 'high_prev', 'low_prev', 'open_today', 'condition', 'transaction_type', 'trade_number', 'level', 'budget', 'return', 'daily_khwab', 'actual_khwab', 'quantity', 'budget_required', 'price', 'trigger_price', 'squareoff', 'stoploss', 'order_id', 'timestamp', 'order_type', 'status', 'profit', 'pl_tag', 'flag', 'adhoora_khwab']

In [20]:
all_trades = pd.DataFrame(columns=header_list)

for i in range(len(data_df.date.unique().tolist())-1):
    
    date_prev = data_df.date.unique().tolist()[i]
    data_prev = data_df[data_df['date']==date_prev]
    open_prev = data_prev.open.iloc[0]
    close_prev = data_prev.open.iloc[-1]
    high_prev = data_prev.high.max()
    low_prev = data_prev.low.min()
    
    date_today = data_df.date.unique().tolist()[i+1]
    data_today = data_df[data_df['date']==date_today]
    
    # Trim beyond exit time
    data_today = data_today[data_today['timestamp'].dt.time<exit_time]
    open_today = data_today.open.iloc[0]
    
    if (open_today > high_prev) & (open_today < 1.15 * high_prev):
        
        condition = 'high'
        transaction_type = 'buy'
        
    elif (open_today < low_prev) & (open_today > 0.85 * low_prev):
        
        condition = 'low'
        transaction_type = 'sell'
        
    else:
        
        condition = None
        transaction_type = None
    
    if condition is not None:
        
        valid_trades = all_trades[(all_trades['instrument']==instrument) & (all_trades['condition']==condition) & (all_trades['status']=='complete')]
        last_valid_trade = valid_trades[valid_trades['trade_number']==valid_trades['trade_number'].max()]

        # Calculate trade number
        if len(last_valid_trade):
            trade_number = int(last_valid_trade['trade_number']) + 1
        else:
            trade_number = 1

        # Calculate level
        if len(last_valid_trade):
            if float(last_valid_trade['pl_tag'])==1.0:
                level = 1
            else:
                level = float(last_valid_trade['level']) + 1
        else:
            level = 1

        # Calculate budget and return
        if level==1:
            budget = assigned_budget
            return_ = assigned_return
        else:
            budget = float(last_valid_trade['budget'])
            return_ = float(last_valid_trade['return'])

        # Calculate daily khwab
        if len(last_valid_trade):
            if int(last_valid_trade['flag'])==1:
                daily_khwab = round(return_ * budget, 2)
            else:
                daily_khwab = 0
        else:
            daily_khwab = round(return_ * budget, 2)

        # Calculate actual khwab
        if len(last_valid_trade):
            actual_khwab = max(round(float(last_valid_trade['adhoora_khwab']) + daily_khwab, 2), round(return_ * budget, 2))
        else:
            actual_khwab = round(return_ * budget, 2)

        # Calculate quantity
        quantity = int(round(actual_khwab/(return_ * open_today)))

        # Calculate budget required
        budget_required = round(quantity * open_today, 2)

        # Calculate price and trigger price
        if condition=='high':
            price = round(open_today + 0.05 * max(round(20 * 0.0010 * open_today), 2), 2)
            trigger_price = round(open_today + 0.05 * max(round(20 * 0.0005 * open_today),1), 2)
        else:
            price = round(open_today - 0.05 * max(round(20 * 0.0010 * open_today), 2), 2)
            trigger_price = round(open_today - 0.05 * max(round(20 * 0.0005 * open_today),1), 2)

        # Calculate square off and stoploss
        squareoff = round(return_ * price, 1)
        stoploss = round(return_ * price, 1)

        # Calculate order_id, order_type
        order_id = trade_number
        order_type = 'SL'
        
        # Calculate timestamp, status and profit
        if transaction_type=='buy':
            
            if data_today.high.max() < trigger_price:
                
                timestamp = data_today.timestamp.iloc[0]
                status = 'incomplete'
                profit = 0
            
            else:
                
                status = 'complete'
                for index, row in data_today.iterrows():

                    if row['high'] > price + squareoff:
                        timestamp = row['timestamp']
                        profit = round(squareoff * quantity, 2)
                        break

                    elif row['low'] < price - stoploss:
                        timestamp = row['timestamp']
                        profit = round(-1 * stoploss * quantity, 2)
                        break

                    else:
                        timestamp = row['timestamp']
                        profit = round((row['close']-price) * quantity, 2)
                        
        else:
            
            if data_today.low.min() > trigger_price:
                timestamp = data_today.timestamp.iloc[0]
                status = 'incomplete'
                profit = 0            
            
            else:
                
                status = 'complete'
                for index, row in data_today.iterrows():

                    if row['low'] < price - squareoff:
                        timestamp = row['timestamp']
                        profit = round(squareoff * quantity, 2)
                        break

                    elif row['high'] > price + stoploss:
                        timestamp = row['timestamp']
                        profit = round(-1 * stoploss * quantity, 2)
                        break

                    else:
                        timestamp = row['timestamp']
                        profit = round((price - row['close']) * quantity, 2)
            
        # Calculate P/L tag
        pl_tag = round(round(float(profit), 2) / (float(squareoff) * float(quantity)), 1)

        # Calculate flag
        if abs(float(pl_tag))==1:
            flag = 1
        else:
            flag = 0

        # Calculate adhoora khwab
        adhoora_khwab = round(float(actual_khwab) - profit, 2)

        trades_today = pd.DataFrame(data={'instrument':[instrument], 
                                          'high_prev':[high_prev], 
                                          'low_prev':[low_prev], 
                                          'open_today':[open_today], 
                                          'condition':[condition], 
                                          'transaction_type':[transaction_type], 
                                          'trade_number':[trade_number], 
                                          'level':[level], 
                                          'budget':[budget], 
                                          'return':[return_], 
                                          'daily_khwab':[daily_khwab], 
                                          'actual_khwab':[actual_khwab], 
                                          'quantity':[quantity], 
                                          'budget_required':[budget_required], 
                                          'price':[price], 
                                          'trigger_price':[trigger_price], 
                                          'squareoff':[squareoff], 
                                          'stoploss':[stoploss], 
                                          'order_id':[order_id], 
                                          'timestamp':[timestamp], 
                                          'order_type':[order_type], 
                                          'status':[status], 
                                          'profit':[profit], 
                                          'pl_tag':[pl_tag], 
                                          'flag':[flag], 
                                          'adhoora_khwab':[adhoora_khwab]
                                         })

        all_trades = all_trades.append(trades_today, ignore_index = True)

# High Trades Analysis

In [21]:
high_trades = all_trades[(all_trades['condition']=='high') & (all_trades['status']=='complete')]

In [22]:
high_trades_loop = high_trades[high_trades['trade_number']<=high_trades[high_trades['pl_tag']==1.0].trade_number.max()]

In [23]:
high_trades

,instrument,high_prev,low_prev,open_today,condition,transaction_type,trade_number,level,budget,return,daily_khwab,actual_khwab,quantity,budget_required,price,trigger_price,squareoff,stoploss,order_id,timestamp,order_type,status,profit,pl_tag,flag,adhoora_khwab
0,NSE:ADANIPORTS,410.70,406.05,411.50,high,buy,1,1,400,0.02,8.0,8.00,1,411.50,411.90,411.70,8.2,8.2,1,2018-01-05 09:42:00+05:30,SL,complete,8.20,1.0,1,-0.20
1,NSE:ADANIPORTS,435.75,422.75,437.70,high,buy,2,1,400,0.02,8.0,8.00,1,437.70,438.15,437.90,8.8,8.8,2,2018-01-18 13:51:00+05:30,SL,complete,-8.80,-1.0,1,16.80
4,NSE:ADANIPORTS,410.35,387.00,412.10,high,buy,3,2,400,0.02,8.0,24.80,3,1236.30,412.50,412.30,8.2,8.2,3,2018-02-07 15:09:00+05:30,SL,complete,-12.15,-0.5,0,36.95
7,NSE:ADANIPORTS,401.60,394.00,401.75,high,buy,4,3,400,0.02,0.0,36.95,5,2008.75,402.15,401.95,8.0,8.0,4,2018-02-12 15:09:00+05:30,SL,complete,7.00,0.2,0,29.95
8,NSE:ADANIPORTS,416.70,405.10,420.90,high,buy,5,4,400,0.02,0.0,29.95,4,1683.60,421.30,421.10,8.4,8.4,5,2018-02-15 14:43:00+05:30,SL,complete,-33.60,-1.0,1,63.55
11,NSE:ADANIPORTS,392.40,369.85,392.50,high,buy,6,5,400,0.02,8.0,71.55,9,3532.50,392.90,392.70,7.9,7.9,6,2018-03-09 10:42:00+05:30,SL,complete,-71.10,-1.0,1,142.65
13,NSE:ADANIPORTS,371.80,360.40,373.00,high,buy,7,6,400,0.02,8.0,150.65,20,7460.00,373.35,373.20,7.5,7.5,7,2018-03-21 13:59:00+05:30,SL,complete,-150.00,-1.0,1,300.65
15,NSE:ADANIPORTS,389.00,379.25,390.75,high,buy,8,7,400,0.02,8.0,308.65,39,15239.25,391.15,390.95,7.8,7.8,8,2018-04-17 14:22:00+05:30,SL,complete,-304.20,-1.0,1,612.85
17,NSE:ADANIPORTS,409.50,392.65,410.00,high,buy,9,8,400,0.02,8.0,620.85,76,31160.00,410.40,410.20,8.2,8.2,9,2018-05-07 15:09:00+05:30,SL,complete,144.40,0.2,0,476.45
19,NSE:ADANIPORTS,382.00,366.65,382.55,high,buy,10,9,400,0.02,0.0,476.45,62,23718.10,382.95,382.75,7.7,7.7,10,2018-05-28 15:09:00+05:30,SL,complete,-198.40,-0.4,0,674.85
21,NSE:ADANIPORTS,377.50,373.50,378.00,high,buy,11,10,400,0.02,0.0,674.85,89,33642.00,378.40,378.20,7.6,7.6,11,2018-06-07 15:09:00+05:30,SL,complete,146.85,0.2,0,528.00
23,NSE:ADANIPORTS,366.60,357.20,369.60,high,buy,12,11,400,0.02,0.0,528.00,71,26241.60,369.95,369.80,7.4,7.4,12,2018-06-21 15:09:00+05:30,SL,complete,-195.25,-0.4,0,723.25
26,NSE:ADANIPORTS,401.50,386.20,402.10,high,buy,13,12,400,0.02,0.0,723.25,90,36189.00,402.50,402.30,8.0,8.0,13,2018-08-01 15:09:00+05:30,SL,complete,-256.50,-0.4,0,979.75
28,NSE:ADANIPORTS,380.50,368.50,381.30,high,buy,14,13,400,0.02,0.0,979.75,128,48806.40,381.70,381.50,7.6,7.6,14,2018-09-06 15:09:00+05:30,SL,complete,262.40,0.3,0,717.35
30,NSE:ADANIPORTS,377.45,365.60,378.00,high,buy,15,14,400,0.02,0.0,717.35,95,35910.00,378.40,378.20,7.6,7.6,15,2018-09-14 15:09:00+05:30,SL,complete,80.75,0.1,0,636.60
32,NSE:ADANIPORTS,335.75,321.90,337.50,high,buy,16,15,400,0.02,0.0,636.60,94,31725.00,337.85,337.65,6.8,6.8,16,2018-10-17 09:49:00+05:30,SL,complete,-639.20,-1.0,1,1275.80
33,NSE:ADANIPORTS,320.65,311.00,325.30,high,buy,17,16,400,0.02,8.0,1283.80,197,64084.10,325.65,325.45,6.5,6.5,17,2018-10-24 10:27:00+05:30,SL,complete,-1280.50,-1.0,1,2564.30
34,NSE:ADANIPORTS,338.85,326.25,338.95,high,buy,18,17,400,0.02,8.0,2572.30,379,128462.05,339.30,339.10,6.8,6.8,18,2018-11-12 10:17:00+05:30,SL,complete,-2577.20,-1.0,1,5149.50
35,NSE:ADANIPORTS,335.00,325.10,335.50,high,buy,19,18,400,0.02,8.0,5157.50,769,257999.50,335.85,335.65,6.7,6.7,19,2018-11-14 15:09:00+05:30,SL,complete,-3345.15,-0.6,0,8502.65
39,NSE:ADANIPORTS,378.50,358.15,379.25,high,buy,20,19,400,0.02,0.0,8502.65,1121,425139.25,379.65,379.45,7.6,7.6,20,2018-12-27 15:09:00+05:30,SL,complete,4091.65,0.5,0,4411.00

# Low Trades Analysis

In [24]:
low_trades = all_trades[(all_trades['condition']=='low') & (all_trades['status']=='complete')]

In [25]:
low_trades_loop = low_trades[low_trades['trade_number']<=low_trades[low_trades['pl_tag']==1.0].trade_number.max()]

In [26]:
low_trades

,instrument,high_prev,low_prev,open_today,condition,transaction_type,trade_number,level,budget,return,daily_khwab,actual_khwab,quantity,budget_required,price,trigger_price,squareoff,stoploss,order_id,timestamp,order_type,status,profit,pl_tag,flag,adhoora_khwab
2,NSE:ADANIPORTS,426.10,412.10,408.85,low,sell,1,1,400,0.02,8.0,8.00,1,408.85,408.45,408.65,8.2,8.2,1,2018-02-05 15:09:00+05:30,SL,complete,0.10,0.0,0,7.90
3,NSE:ADANIPORTS,412.85,406.35,397.95,low,sell,2,2,400,0.02,0.0,8.00,1,397.95,397.55,397.75,8.0,8.0,2,2018-02-06 09:15:00+05:30,SL,complete,8.00,1.0,1,0.00
6,NSE:ADANIPORTS,413.50,401.10,395.30,low,sell,3,1,400,0.02,8.0,8.00,1,395.30,394.90,395.10,7.9,7.9,3,2018-02-09 15:09:00+05:30,SL,complete,-3.45,-0.4,0,11.45
9,NSE:ADANIPORTS,416.60,409.70,408.90,low,sell,4,2,400,0.02,0.0,11.45,1,408.90,408.50,408.70,8.2,8.2,4,2018-02-28 15:09:00+05:30,SL,complete,1.20,0.1,0,10.25
10,NSE:ADANIPORTS,413.75,405.00,403.25,low,sell,5,3,400,0.02,0.0,10.25,1,403.25,402.85,403.05,8.1,8.1,5,2018-03-05 09:34:00+05:30,SL,complete,-8.10,-1.0,1,18.35
12,NSE:ADANIPORTS,386.35,380.40,377.40,low,sell,6,4,400,0.02,8.0,26.35,3,1132.20,377.00,377.20,7.5,7.5,6,2018-03-16 14:13:00+05:30,SL,complete,22.50,1.0,1,3.85
14,NSE:ADANIPORTS,364.95,354.10,353.55,low,sell,7,1,400,0.02,8.0,11.85,2,707.10,353.20,353.35,7.1,7.1,7,2018-03-23 15:02:00+05:30,SL,complete,-14.20,-1.0,1,26.05
16,NSE:ADANIPORTS,397.45,390.20,388.65,low,sell,8,2,400,0.02,8.0,34.05,4,1554.60,388.25,388.45,7.8,7.8,8,2018-04-26 14:07:00+05:30,SL,complete,-31.20,-1.0,1,65.25
20,NSE:ADANIPORTS,383.85,373.20,373.00,low,sell,9,3,400,0.02,8.0,73.25,10,3730.00,372.65,372.80,7.5,7.5,9,2018-05-30 15:09:00+05:30,SL,complete,-10.50,-0.1,0,83.75
22,NSE:ADANIPORTS,383.25,372.15,371.30,low,sell,10,4,400,0.02,0.0,83.75,11,4084.30,370.95,371.10,7.4,7.4,10,2018-06-15 15:09:00+05:30,SL,complete,-28.05,-0.3,0,111.80
24,NSE:ADANIPORTS,374.75,365.95,364.30,low,sell,11,5,400,0.02,0.0,111.80,15,5464.50,363.95,364.10,7.3,7.3,11,2018-06-22 15:09:00+05:30,SL,complete,-29.25,-0.3,0,141.05
27,NSE:ADANIPORTS,406.30,395.30,393.00,low,sell,12,6,400,0.02,0.0,141.05,18,7074.00,392.60,392.80,7.9,7.9,12,2018-08-07 09:36:00+05:30,SL,complete,142.20,1.0,1,-1.15
29,NSE:ADANIPORTS,385.60,376.10,375.60,low,sell,13,1,400,0.02,8.0,8.00,1,375.60,375.20,375.40,7.5,7.5,13,2018-09-10 11:41:00+05:30,SL,complete,-7.50,-1.0,1,15.50
31,NSE:ADANIPORTS,338.00,326.50,324.75,low,sell,14,2,400,0.02,8.0,23.50,4,1299.00,324.45,324.60,6.5,6.5,14,2018-10-04 12:59:00+05:30,SL,complete,26.00,1.0,1,-2.50
36,NSE:ADANIPORTS,374.60,363.75,362.00,low,sell,15,1,400,0.02,8.0,8.00,1,362.00,361.65,361.80,7.2,7.2,15,2018-12-10 15:09:00+05:30,SL,complete,1.85,0.3,0,6.15
38,NSE:ADANIPORTS,377.45,369.20,369.15,low,sell,16,2,400,0.02,0.0,8.00,1,369.15,368.80,368.95,7.4,7.4,16,2018-12-18 15:09:00+05:30,SL,complete,-4.00,-0.5,0,12.00

# Results

In [27]:
pd.DataFrame(data={'high':[len(high_trades),
                           len(high_trades_loop),
                           round(high_trades_loop.profit.sum(), 2), 
                           round(high_trades_loop.profit.sum()/budget * 100, 2),
                           round(high_trades_loop.budget_required.max()), 
                           round(high_trades_loop.budget_required.max()/leverage)],
                   'low':[len(low_trades),
                          len(low_trades_loop),
                          round(low_trades_loop.profit.sum(), 2), 
                          round(low_trades_loop.profit.sum()/budget * 100, 2),
                          round(low_trades_loop.budget_required.max()),
                          round(low_trades_loop.budget_required.max()/leverage)]
                   }, 
             index = ['total_trades', 'trades_considered', 'profit', 'perc_return', 'hightest_budget_required', 'hightest_margin_required'])

                            high      low
total_trades               20.00    16.00
trades_considered           1.00    14.00
profit                      8.20    67.75
perc_return                 2.05    16.94
hightest_budget_required  412.00  7074.00
hightest_margin_required   27.00   472.00