In [1]:
import pandas as pd
import datetime as dt
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 5000)

In [2]:
from LogIn import LogIn
kite = LogIn().return_kite_obj()

In [3]:
budget_df = pd.read_csv('budget.csv')

In [4]:
budget_df

        instrument  budget  return
0    NSE:UNIONBANK     400    0.02
1      NSE:DCBBANK     400    0.02
2      NSE:YESBANK     400    0.02
3        NSE:WIPRO     400    0.02
4    NSE:TATASTEEL     400    0.02
5         NSE:SBIN     400    0.02
6          NSE:PNB     400    0.02
7         NSE:ONGC     400    0.02
8          NSE:OIL     400    0.02
9         NSE:NTPC     400    0.02
10         NSE:BEL     400    0.02
11      NSE:BIOCON     400    0.02
12       NSE:CANBK     400    0.02
13  NSE:CASTROLIND     400    0.02
14    NSE:CHOLAFIN     400    0.02
15   NSE:COALINDIA     400    0.02
16  NSE:ENGINERSIN     400    0.02
17    NSE:EXIDEIND     400    0.02
18    NSE:JSWSTEEL     400    0.02
19  NSE:MANAPPURAM     400    0.02
20        NSE:SAIL     400    0.02
21      NSE:RECLTD     400    0.02
22        NSE:NMDC     400    0.02
23        NSE:MFSL     500    0.02
24        NSE:IDBI     400    0.02
25      NSE:ARVIND     400    0.02
26        NSE:BHEL     400    0.02
27  NSE:TATAMTRDVR     400    0.02
28   NSE:TATAPOWER     400    0.02
29  NSE:ADANIPOWER     400    0.02
30       NSE:BSOFT     400    0.02
31    NSE:ASHOKLEY     400    0.02
32         NSE:NCC     400    0.02
33   NSE:BANKINDIA     400    0.02
34  NSE:FEDERALBNK     400    0.02
35  NSE:MOTHERSUMI     400    0.02
36  NSE:BANKBARODA     400    0.02
37  NSE:JINDALSTEL     400    0.02
38       NSE:L&TFH     400    0.02
39         NSE:PFC     400    0.02
40     NSE:EQUITAS     400    0.02
41  NSE:TATAMOTORS     400    0.02
42         NSE:IOC     400    0.02
43    NSE:ADANIENT     400    0.02
44        NSE:GAIL     400    0.02
45        NSE:VEDL     400    0.02
46  NSE:APOLLOTYRE     400    0.02
47         NSE:DLF     400    0.02
48    NSE:HINDALCO     400    0.02
49   NSE:AMBUJACEM     400    0.02
50    NSE:HINDZINC     400    0.02
51    NSE:CADILAHC     400    0.02
52   NSE:POWERGRID     400    0.02
53   NSE:HINDPETRO     400    0.02
54    NSE:INFRATEL     400    0.02
55         NSE:ITC     400    0.02
56    NSE:PETRONET     400    0.02
57  NSE:TATAGLOBAL     400    0.02
58     NSE:UJJIVAN     400    0.02
59  NSE:TORNTPOWER     400    0.02
60         NSE:IGL     400    0.02
61  NSE:ADANIPORTS     400    0.02
62  NSE:BERGEPAINT     400    0.02
63        NSE:BPCL     400    0.02
64        NSE:ZEEL     400    0.02
65    NSE:GLENMARK     400    0.02
66  NSE:BHARTIARTL     400    0.02
67    NSE:TVSMOTOR     400    0.02
68    NSE:HEXAWARE     400    0.02
69  NSE:ICICIPRULI     400    0.02

# Inputs

In [5]:
instrument = 'NSE:IGL'
from_date = '2018-01-01'
to_date = '2018-12-31'

In [6]:
assigned_budget = 400
assigned_return = 0.02
leverage = 15
exit_time = dt.time(15, 10)

# Process

In [7]:
instrument_token = kite.ohlc(instrument)[instrument]['instrument_token']

In [8]:
data = kite.historical_data(instrument_token=instrument_token, from_date=from_date, to_date=to_date, interval='minute', continuous=False)

In [9]:
data_df = pd.DataFrame(data)

In [10]:
len(data_df)

91935

In [11]:
data_df.rename(columns={'date':'timestamp'}, inplace=True)
data_df['date'] = data_df['timestamp'].dt.date
data_df['day'] = data_df['timestamp'].dt.day_name()

In [12]:
data_df.head()

,close,timestamp,high,low,open,volume,date,day
0,334.25,2018-01-01 09:15:00+05:30,334.8,334.25,334.50,3443,2018-01-01,Monday
1,334.80,2018-01-01 09:16:00+05:30,334.8,334.25,334.25,2698,2018-01-01,Monday
2,334.90,2018-01-01 09:17:00+05:30,335.0,334.55,334.80,3812,2018-01-01,Monday
3,334.65,2018-01-01 09:18:00+05:30,335.2,334.55,335.00,5770,2018-01-01,Monday
4,334.85,2018-01-01 09:19:00+05:30,334.9,334.50,334.65,2311,2018-01-01,Monday

In [13]:
sanity_check = data_df.groupby('date').count().reset_index()

In [14]:
incomplete_data_days = sanity_check[sanity_check['volume']!=375]

In [15]:
incomplete_data_days

           date  close  timestamp  high  low  open  volume  day
210  2018-11-07     60         60    60   60    60      60   60

In [16]:
data_df = data_df[~data_df['date'].isin(incomplete_data_days.date.tolist())]

In [17]:
len(data_df)

91875

In [18]:
len(data_df)/375

245.0

In [19]:
header_list = ['instrument', 'high_prev', 'low_prev', 'open_today', 'condition', 'transaction_type', 'trade_number', 'level', 'budget', 'return', 'daily_khwab', 'actual_khwab', 'quantity', 'budget_required', 'price', 'trigger_price', 'squareoff', 'stoploss', 'order_id', 'timestamp', 'order_type', 'status', 'profit', 'pl_tag', 'flag', 'adhoora_khwab']

In [20]:
all_trades = pd.DataFrame(columns=header_list)

for i in range(len(data_df.date.unique().tolist())-1):
    
    date_prev = data_df.date.unique().tolist()[i]
    data_prev = data_df[data_df['date']==date_prev]
    open_prev = data_prev.open.iloc[0]
    close_prev = data_prev.open.iloc[-1]
    high_prev = data_prev.high.max()
    low_prev = data_prev.low.min()
    
    date_today = data_df.date.unique().tolist()[i+1]
    data_today = data_df[data_df['date']==date_today]
    
    # Trim beyond exit time
    data_today = data_today[data_today['timestamp'].dt.time<exit_time]
    open_today = data_today.open.iloc[0]
    
    if (open_today > high_prev) & (open_today < 1.15 * high_prev):
        
        condition = 'high'
        transaction_type = 'buy'
        
    elif (open_today < low_prev) & (open_today > 0.85 * low_prev):
        
        condition = 'low'
        transaction_type = 'sell'
        
    else:
        
        condition = None
        transaction_type = None
    
    if condition is not None:
        
        valid_trades = all_trades[(all_trades['instrument']==instrument) & (all_trades['condition']==condition) & (all_trades['status']=='complete')]
        last_valid_trade = valid_trades[valid_trades['trade_number']==valid_trades['trade_number'].max()]

        # Calculate trade number
        if len(last_valid_trade):
            trade_number = int(last_valid_trade['trade_number']) + 1
        else:
            trade_number = 1

        # Calculate level
        if len(last_valid_trade):
            if float(last_valid_trade['pl_tag'])==1.0:
                level = 1
            else:
                level = float(last_valid_trade['level']) + 1
        else:
            level = 1

        # Calculate budget and return
        if level==1:
            budget = assigned_budget
            return_ = assigned_return
        else:
            budget = float(last_valid_trade['budget'])
            return_ = float(last_valid_trade['return'])

        # Calculate daily khwab
        if len(last_valid_trade):
            if int(last_valid_trade['flag'])==1:
                daily_khwab = round(return_ * budget, 2)
            else:
                daily_khwab = 0
        else:
            daily_khwab = round(return_ * budget, 2)

        # Calculate actual khwab
        if len(last_valid_trade):
            actual_khwab = max(round(float(last_valid_trade['adhoora_khwab']) + daily_khwab, 2), round(return_ * budget, 2))
        else:
            actual_khwab = round(return_ * budget, 2)

        # Calculate quantity
        quantity = int(round(actual_khwab/(return_ * open_today)))

        # Calculate budget required
        budget_required = round(quantity * open_today, 2)

        # Calculate price and trigger price
        if condition=='high':
            price = round(open_today + 0.05 * max(round(20 * 0.0010 * open_today), 2), 2)
            trigger_price = round(open_today + 0.05 * max(round(20 * 0.0005 * open_today),1), 2)
        else:
            price = round(open_today - 0.05 * max(round(20 * 0.0010 * open_today), 2), 2)
            trigger_price = round(open_today - 0.05 * max(round(20 * 0.0005 * open_today),1), 2)

        # Calculate square off and stoploss
        squareoff = round(return_ * price, 1)
        stoploss = round(return_ * price, 1)

        # Calculate order_id, order_type
        order_id = trade_number
        order_type = 'SL'
        
        # Calculate timestamp, status and profit
        if transaction_type=='buy':
            
            if data_today.high.max() < trigger_price:
                
                timestamp = data_today.timestamp.iloc[0]
                status = 'incomplete'
                profit = 0
            
            else:
                
                status = 'complete'
                for index, row in data_today.iterrows():

                    if row['high'] > price + squareoff:
                        timestamp = row['timestamp']
                        profit = round(squareoff * quantity, 2)
                        break

                    elif row['low'] < price - stoploss:
                        timestamp = row['timestamp']
                        profit = round(-1 * stoploss * quantity, 2)
                        break

                    else:
                        timestamp = row['timestamp']
                        profit = round((row['close']-price) * quantity, 2)
                        
        else:
            
            if data_today.low.min() > trigger_price:
                timestamp = data_today.timestamp.iloc[0]
                status = 'incomplete'
                profit = 0            
            
            else:
                
                status = 'complete'
                for index, row in data_today.iterrows():

                    if row['low'] < price - squareoff:
                        timestamp = row['timestamp']
                        profit = round(squareoff * quantity, 2)
                        break

                    elif row['high'] > price + stoploss:
                        timestamp = row['timestamp']
                        profit = round(-1 * stoploss * quantity, 2)
                        break

                    else:
                        timestamp = row['timestamp']
                        profit = round((price - row['close']) * quantity, 2)
            
        # Calculate P/L tag
        pl_tag = round(round(float(profit), 2) / (float(squareoff) * float(quantity)), 1)

        # Calculate flag
        if abs(float(pl_tag))==1:
            flag = 1
        else:
            flag = 0

        # Calculate adhoora khwab
        adhoora_khwab = round(float(actual_khwab) - profit, 2)

        trades_today = pd.DataFrame(data={'instrument':[instrument], 
                                          'high_prev':[high_prev], 
                                          'low_prev':[low_prev], 
                                          'open_today':[open_today], 
                                          'condition':[condition], 
                                          'transaction_type':[transaction_type], 
                                          'trade_number':[trade_number], 
                                          'level':[level], 
                                          'budget':[budget], 
                                          'return':[return_], 
                                          'daily_khwab':[daily_khwab], 
                                          'actual_khwab':[actual_khwab], 
                                          'quantity':[quantity], 
                                          'budget_required':[budget_required], 
                                          'price':[price], 
                                          'trigger_price':[trigger_price], 
                                          'squareoff':[squareoff], 
                                          'stoploss':[stoploss], 
                                          'order_id':[order_id], 
                                          'timestamp':[timestamp], 
                                          'order_type':[order_type], 
                                          'status':[status], 
                                          'profit':[profit], 
                                          'pl_tag':[pl_tag], 
                                          'flag':[flag], 
                                          'adhoora_khwab':[adhoora_khwab]
                                         })

        all_trades = all_trades.append(trades_today, ignore_index = True)

# High Trades Analysis

In [21]:
high_trades = all_trades[(all_trades['condition']=='high') & (all_trades['status']=='complete')]

In [22]:
high_trades_loop = high_trades[high_trades['trade_number']<=high_trades[high_trades['pl_tag']==1.0].trade_number.max()]

In [23]:
high_trades

,instrument,high_prev,low_prev,open_today,condition,transaction_type,trade_number,level,budget,return,daily_khwab,actual_khwab,quantity,budget_required,price,trigger_price,squareoff,stoploss,order_id,timestamp,order_type,status,profit,pl_tag,flag,adhoora_khwab
0,NSE:IGL,326.75,322.25,327.40,high,buy,1,1,400,0.02,8.0,8.00,1,327.40,327.75,327.55,6.6,6.6,1,2018-01-11 15:09:00+05:30,SL,complete,-5.20,-0.8,0,13.20
3,NSE:IGL,294.00,271.70,297.00,high,buy,2,2,400,0.02,0.0,13.20,2,594.00,297.30,297.15,5.9,5.9,2,2018-02-07 15:09:00+05:30,SL,complete,-7.20,-0.6,0,20.40
4,NSE:IGL,303.40,289.30,306.85,high,buy,3,3,400,0.02,0.0,20.40,3,920.55,307.15,307.00,6.1,6.1,3,2018-02-14 15:09:00+05:30,SL,complete,3.45,0.2,0,16.95
5,NSE:IGL,299.80,290.65,300.15,high,buy,4,4,400,0.02,0.0,16.95,3,900.45,300.45,300.30,6.0,6.0,4,2018-02-21 14:20:00+05:30,SL,complete,-18.00,-1.0,1,34.95
6,NSE:IGL,298.75,291.70,299.00,high,buy,5,5,400,0.02,8.0,42.95,7,2093.00,299.30,299.15,6.0,6.0,5,2018-02-27 09:24:00+05:30,SL,complete,42.00,1.0,1,0.95
10,NSE:IGL,281.50,275.40,284.00,high,buy,6,1,400,0.02,8.0,8.95,2,568.00,284.30,284.15,5.7,5.7,6,2018-04-02 12:30:00+05:30,SL,complete,-11.40,-1.0,1,20.35
11,NSE:IGL,279.75,273.00,279.95,high,buy,7,2,400,0.02,8.0,28.35,5,1399.75,280.25,280.10,5.6,5.6,7,2018-04-04 09:58:00+05:30,SL,complete,28.00,1.0,1,0.35
12,NSE:IGL,297.90,290.25,299.30,high,buy,8,1,400,0.02,8.0,8.35,1,299.30,299.60,299.45,6.0,6.0,8,2018-04-09 15:09:00+05:30,SL,complete,3.85,0.6,0,4.50
13,NSE:IGL,304.75,299.30,305.30,high,buy,9,2,400,0.02,0.0,8.00,1,305.30,305.60,305.45,6.1,6.1,9,2018-04-10 10:29:00+05:30,SL,complete,-6.10,-1.0,1,14.10
16,NSE:IGL,267.40,258.00,267.50,high,buy,10,3,400,0.02,8.0,22.10,4,1070.00,267.75,267.65,5.4,5.4,10,2018-05-14 15:09:00+05:30,SL,complete,9.00,0.4,0,13.10
19,NSE:IGL,265.50,256.65,265.80,high,buy,11,4,400,0.02,0.0,13.10,2,531.60,266.05,265.95,5.3,5.3,11,2018-05-24 09:32:00+05:30,SL,complete,-10.60,-1.0,1,23.70
20,NSE:IGL,258.95,252.25,261.00,high,buy,12,5,400,0.02,8.0,31.70,6,1566.00,261.25,261.15,5.2,5.2,12,2018-05-28 15:09:00+05:30,SL,complete,-3.60,-0.1,0,35.30
21,NSE:IGL,263.00,258.20,265.95,high,buy,13,6,400,0.02,0.0,35.30,7,1861.65,266.20,266.10,5.3,5.3,13,2018-05-29 15:09:00+05:30,SL,complete,15.75,0.4,0,19.55
22,NSE:IGL,266.65,260.40,266.95,high,buy,14,7,400,0.02,0.0,19.55,4,1067.80,267.20,267.10,5.3,5.3,14,2018-06-04 15:09:00+05:30,SL,complete,4.40,0.2,0,15.15
23,NSE:IGL,263.55,256.00,265.00,high,buy,15,8,400,0.02,0.0,15.15,3,795.00,265.25,265.15,5.3,5.3,15,2018-06-07 15:09:00+05:30,SL,complete,-5.25,-0.3,0,20.40
24,NSE:IGL,281.00,262.80,282.65,high,buy,16,9,400,0.02,0.0,20.40,4,1130.60,282.95,282.80,5.7,5.7,16,2018-06-11 15:08:00+05:30,SL,complete,-22.80,-1.0,1,43.20
27,NSE:IGL,264.50,260.00,265.00,high,buy,17,10,400,0.02,8.0,51.20,10,2650.00,265.25,265.15,5.3,5.3,17,2018-07-12 15:09:00+05:30,SL,complete,-30.50,-0.6,0,81.70
28,NSE:IGL,296.40,280.30,296.45,high,buy,18,11,400,0.02,0.0,81.70,14,4150.30,296.75,296.60,5.9,5.9,18,2018-07-26 15:09:00+05:30,SL,complete,-23.10,-0.3,0,104.80
29,NSE:IGL,300.00,293.00,302.25,high,buy,19,12,400,0.02,0.0,104.80,17,5138.25,302.55,302.40,6.1,6.1,19,2018-07-31 09:21:00+05:30,SL,complete,103.70,1.0,1,1.10
30,NSE:IGL,304.45,292.50,306.05,high,buy,20,1,400,0.02,8.0,9.10,1,306.05,306.35,306.20,6.1,6.1,20,2018-08-10 10:43:00+05:30,SL,complete,-6.10,-1.0,1,15.20
31,NSE:IGL,286.10,275.90,287.20,high,buy,21,2,400,0.02,8.0,23.20,4,1148.80,287.50,287.35,5.8,5.8,21,2018-08-21 15:09:00+05:30,SL,complete,-8.40,-0.4,0,31.60
34,NSE:IGL,266.10,255.70,268.05,high,buy,22,3,400,0.02,0.0,31.60,6,1608.30,268.30,268.20,5.4,5.4,22,2018-09-26 09:18:00+05:30,SL,complete,-32.40,-1.0,1,64.00
36,NSE:IGL,249.05,242.35,250.05,high,buy,23,4,400,0.02,8.0,72.00,14,3500.70,250.30,250.20,5.0,5.0,23,2018-10-17 13:27:00+05:30,SL,complete,-70.00,-1.0,1,142.00
38,NSE:IGL,286.50,278.10,287.00,high,buy,24,5,400,0.02,8.0,150.00,26,7462.00,287.30,287.15,5.7,5.7,24,2018-11-06 09:47:00+05:30,SL,complete,-148.20,-1.0,1,298.20
41,NSE:IGL,253.35,248.50,254.00,high,buy,25,6,400,0.02,8.0,306.20,60,15240.00,254.25,254.15,5.1,5.1,25,2018-12-13 15:09:00+05:30,SL,complete,24.00,0.1,0,282.20
42,NSE:IGL,254.30,250.65,254.50,high,buy,26,7,400,0.02,0.0,282.20,55,13997.50,254.75,254.65,5.1,5.1,26,2018-12-17 10:35:00+05:30,SL,complete,280.50,1.0,1,1.70
44,NSE:IGL,264.15,258.40,265.90,high,buy,27,1,400,0.02,8.0,9.70,2,531.80,266.15,266.05,5.3,5.3,27,2018-12-27 15:09:00+05:30,SL,complete,-0.40,-0.0,0,10.10

# Low Trades Analysis

In [24]:
low_trades = all_trades[(all_trades['condition']=='low') & (all_trades['status']=='complete')]

In [25]:
low_trades_loop = low_trades[low_trades['trade_number']<=low_trades[low_trades['pl_tag']==1.0].trade_number.max()]

In [26]:
low_trades

,instrument,high_prev,low_prev,open_today,condition,transaction_type,trade_number,level,budget,return,daily_khwab,actual_khwab,quantity,budget_required,price,trigger_price,squareoff,stoploss,order_id,timestamp,order_type,status,profit,pl_tag,flag,adhoora_khwab
1,NSE:IGL,306.75,299.50,299.05,low,sell,1,1,400,0.02,8.0,8.0,1,299.05,298.75,298.90,6.0,6.0,1,2018-02-02 10:11:00+05:30,SL,complete,6.00,1.0,1,2.00
7,NSE:IGL,299.35,295.35,294.40,low,sell,2,1,400,0.02,8.0,10.0,2,588.80,294.10,294.25,5.9,5.9,2,2018-03-19 10:28:00+05:30,SL,complete,11.80,1.0,1,-1.80
9,NSE:IGL,296.75,289.65,285.20,low,sell,3,1,400,0.02,8.0,8.0,1,285.20,284.90,285.05,5.7,5.7,3,2018-03-23 15:09:00+05:30,SL,complete,2.80,0.5,0,5.20
15,NSE:IGL,292.30,286.50,285.70,low,sell,4,2,400,0.02,0.0,8.0,1,285.70,285.40,285.55,5.7,5.7,4,2018-05-02 11:02:00+05:30,SL,complete,5.70,1.0,1,2.30
17,NSE:IGL,276.85,265.10,263.35,low,sell,5,1,400,0.02,8.0,10.3,2,526.70,263.10,263.20,5.3,5.3,5,2018-05-21 15:09:00+05:30,SL,complete,8.60,0.8,0,1.70
18,NSE:IGL,266.30,258.55,257.90,low,sell,6,2,400,0.02,0.0,8.0,2,515.80,257.65,257.75,5.2,5.2,6,2018-05-22 09:28:00+05:30,SL,complete,10.40,1.0,1,-2.40
25,NSE:IGL,274.75,267.40,267.30,low,sell,7,1,400,0.02,8.0,8.0,1,267.30,267.05,267.15,5.3,5.3,7,2018-06-14 15:09:00+05:30,SL,complete,0.05,0.0,0,7.95
26,NSE:IGL,264.85,258.70,257.90,low,sell,8,2,400,0.02,0.0,8.0,2,515.80,257.65,257.75,5.2,5.2,8,2018-06-19 12:52:00+05:30,SL,complete,10.40,1.0,1,-2.40
33,NSE:IGL,291.30,280.35,279.00,low,sell,9,1,400,0.02,8.0,8.0,1,279.00,278.70,278.85,5.6,5.6,9,2018-09-05 09:50:00+05:30,SL,complete,5.60,1.0,1,2.40
35,NSE:IGL,243.00,232.65,227.00,low,sell,10,1,400,0.02,8.0,10.4,2,454.00,226.75,226.90,4.5,4.5,10,2018-10-05 09:15:00+05:30,SL,complete,9.00,1.0,1,1.40
37,NSE:IGL,251.00,241.05,240.95,low,sell,11,1,400,0.02,8.0,9.4,2,481.90,240.70,240.85,4.8,4.8,11,2018-10-19 09:25:00+05:30,SL,complete,-9.60,-1.0,1,19.00
39,NSE:IGL,255.50,246.15,243.30,low,sell,12,2,400,0.02,8.0,27.0,6,1459.80,243.05,243.20,4.9,4.9,12,2018-12-10 09:15:00+05:30,SL,complete,-29.40,-1.0,1,56.40

# Results

In [27]:
pd.DataFrame(data={'high':[len(high_trades),
                           len(high_trades_loop),
                           round(high_trades_loop.profit.sum(), 2), 
                           round(high_trades_loop.profit.sum()/budget * 100, 2),
                           round(high_trades_loop.budget_required.max()), 
                           round(high_trades_loop.budget_required.max()/leverage)],
                   'low':[len(low_trades),
                          len(low_trades_loop),
                          round(low_trades_loop.profit.sum(), 2), 
                          round(low_trades_loop.profit.sum()/budget * 100, 2),
                          round(low_trades_loop.budget_required.max()),
                          round(low_trades_loop.budget_required.max()/leverage)]
                   }, 
             index = ['total_trades', 'trades_considered', 'profit', 'perc_return', 'hightest_budget_required', 'hightest_margin_required'])

                              high     low
total_trades                 27.00   12.00
trades_considered            26.00   10.00
profit                      105.80   70.35
perc_return                  26.45   17.59
hightest_budget_required  15240.00  589.00
hightest_margin_required   1016.00   39.00

In [28]:
#NSE:ADANIPORTS